language: haskell

env:
  - GHCVER=8.0.2 STACK_YAML=stack.yaml


#branches:
#  only:
#    - master

sudo: false

cache:
  directories:
    - $HOME/.stack/

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack test :shc-test --no-terminal --coverage --haddock --no-haddock-deps

#after_script:
#  - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.2.0/shc-linux-x64-$GHCVER.tar.bz2 | tar -xj
#  - ./shc stack-hpc-coveralls shc-test
